### ISSUE TITLE
The errors seem to be occurring on A02s and A11s

### ISSUE THREAD

**Issue by MihaiSandor** [kardianos/hl7#3]
Hey, please check this out:  https://go.dev/play/p/idI3PKTocTu

Can you take a look please?

**Comment by kardianos** [comment]
> trigger group: line 6 (*h250.DG1) not found in trigger "ADT_A02"

ADT_A02 does not define in the segment a DG1 element. ADT_A01 does. But by the spec, ADT_02 does not. To solve, this look for `type ADT_A02` and look at the fields.
