### ISSUE TITLE
HL7 V2.5.0 Error Decoding

### ISSUE THREAD

**Issue by MihaiSandor** [kardianos/hl7#7]
Hi @kardianos,

I noticed that this type of message fails to decode when using version 2.5.0:

```go
hl7Decoder := hl7.NewDecoder(h250.Registry, nil)
data, err := hl7Decoder.Decode(body)
```

Here is the sample message:

```bash
MSH|^~\&|PATIENTPING_ADT|111111^Autumn Care of Test^SNF|RECEIVING_APP|222222^App Medicare|20240509110900||ADT^A21|ebddac26-0e15-11ef-bec7-e36b36b6aZFA|111111|Autumn Care of Test|SNF|401 Test Road^^Test^US^27209|166992295140409183400||||||232926913ntTest^^||7045457091||||||
```

**Comment by kardianos** [comment]
Here is the error message I received:
`MSH.ContinuationPointer: string.14:  contains an escape character 401 Test Road^^Test^US^27209; data may be malformed, invalid type, or contain a bug`

It is reading value ` 401 Test Road^^Test^US^27209` in the string field `MSH.14`, which is accurate. It is not escaping the "^" symbol, which is incorrect. As such, it is letting you know there is a bug, either with the encoder or with the assumed message structure.

I could see a decoding option that turned this check off.
